name: Partition Manager CI

on: [push]

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Linting Tools
      run: |
        python -m pip install --upgrade pip
        pip install --user pylint==2.17.7
        pip install --user black~=22.3
        pip install --user flake8~=4.0

    - name: Install Partition Manager
      run: |
        pip install --editable ".[pymysql]"

    - name: Analysing the code with pylint
      run: |
        python -m pylint -E partitionmanager

    - name: Checking format with Black
      run: |
        python -m black --check .

    - name: Checking format with Flake8
      run: |
        python -m flake8

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Partition Manager
      run: |
        pip install --editable ".[pymysql]"
    - name: Install PyTest
      run: |
        pip install pytest
    - name: Run PyTest
      run: |
        pytest --junitxml=test-results/junit.xml
